version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Fetching dependencies from AWS CodeArtifact"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain instape --domain-owner 367260454855 --query authorizationToken --output text)
      - mvn clean install -s ~/.m2/settings.xml
  post_build:
    commands:
      - echo "Publishing dependencies to AWS CodeArtifact"
      - mvn deploy -s ~/.m2/settings.xml
